name: oncodrive
channels: !!python/tuple
- defaults
- bbglab
- bioconda
- conda-forge
- r
dependencies:
- alabaster=0.7.9=py35_0
- babel=2.3.4=py35_0
- ago=0.0.8=py35_0
- bgconfig=0.3.0=py35_0
- bgdata=0.18.0=py35_0
- bgqmap=1.0.0=py35_0
- itab=0.9.0=py35_0
- intervaltree=2.1.0=py35_0
- sortedcontainers=1.5.3=py35_0
- bokeh=0.12.3=py35_0
- configobj=5.0.6=py35_0
- cycler=0.10.0=py35_0
- dbus=1.10.10=0
- docutils=0.12=py35_2
- drmaa=0.7.6=py35_0
- expat=2.1.0=0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- glib=2.43.0=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- imagesize=0.7.1=py35_0
- jinja2=2.8=py35_1
- jpeg=8d=2
- libffi=3.2.1=0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libxcb=1.12=1
- libxml2=2.9.2=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_1
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pandas=0.19.0=np111py35_0
- patsy=0.4.1=py35_0
- pip=8.1.2=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.7=py35_0
- pyyaml=3.12=py35_0
- qt=5.6.0=1
- readline=6.2=2
- requests=2.11.1=py35_0
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.4.8=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlite=3.13.0=0
- statsmodels=0.6.1=np111py35_1
- tk=8.5.18=0
- tornado=4.4.2=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - pytabix==0.1
  - sphinx-rtd-theme==0.1.9

