name: oncodrivefml
channels:
- defaults
- bbglab
- bioconda
- conda-forge
- r
dependencies:
- bgconfig=0.9
- numpy=1.18.1
- scipy=1.4.1
- statsmodels=0.11.0
- pytabix=0.0.2
- bokeh=1.4.0
- pandas=1.0.1
- matplotlib=3.1.3
- intervaltree=3.0.2
- bgdata=2.0.3
- bgreference=0.6
- click=7.0
- bgparsers=0.10
- bgsignature=0.2
- bgcache=0.1
- ago=0.0.93
- cython=0.29.15
- python=3.6.*
- sphinx=1.5.1
- bglogs=0.6